from __future__ import annotations

import csv
import json
import os
import re
from pathlib import Path
from typing import Any, Callable

import numpy as np
import pandas as pd
from tqdm.auto import tqdm

from . import config
from .api_clients import (
    HuaweiMaaSClient,
    MaaSAPIError,
    load_cache,
    now_utc,
    remove_surrogate_cache_rows,
    sha256_text,
)
from .normalization import normalize_text_value


MIDDLE_TRAIN_FILE = "train_middle_features.csv"
MIDDLE_EXTERNAL_FILE = "external_middle_features.csv"
MIDDLE_MANIFEST_FILE = "middle_feature_manifest.json"
CACHE_FILE = "huawei_bge_m3_embedding_cache.csv"

# v2-compatible tokenizer/windowing. This preserves the window strings and cache keys
# generated by stagev2 for the supplied Cookie Theft transcripts.
TOKEN_RE = re.compile(r"[A-Za-z']+|\d+")

REAL_API_SOURCES = {"api", "huawei_maas_api", "huawei_maas_api_v2"}
SURROGATE_SOURCES = {"local_surrogate", "surrogate", "local_surrogate_no_api_key"}

SAFETY_MASK_WORDS = {
    # Generic provider safety false-positive triggers.
    "attack", "blood", "crash", "dead", "death", "die", "drug", "fall", "falling",
    "gun", "hate", "kill", "knife", "murder", "sex", "shoot", "suicide", "weapon",
    # Cookie Theft / transcript-domain words. These words are harmless here, but short
    # transcript windows can be misclassified by provider content-safety filters.
    "boy", "boys", "girl", "girls", "child", "children", "kid", "kids", "mother",
    "woman", "lady", "cookie", "cookies", "cooky", "jar", "stool", "chair", "sink",
    "water", "dish", "dishes", "cup", "plate", "curtain", "curtains", "window",
    "floor", "counter", "cabinet", "apron", "faucet", "towel", "kitchen", "room",
    "taking", "take", "reaching", "reach", "steal", "stealing", "washing", "wash",
    "overflow", "overflowing", "spill", "spilling", "climb", "climbing", "stand",
    "standing", "sit", "sitting", "look", "looking", "doing", "getting", "get",
}


def _contains_surrogate_marker(value: object) -> bool:
    if isinstance(value, dict):
        for key, item in value.items():
            if str(key).lower() in {"api_mode", "source", "embedding_source"}:
                if str(item).strip().lower() in SURROGATE_SOURCES:
                    return True
            if _contains_surrogate_marker(item):
                return True
    elif isinstance(value, list):
        return any(_contains_surrogate_marker(item) for item in value)
    return False


def _normalize_text_v2(text: Any) -> str:
    if pd.isna(text):
        return ""
    return re.sub(r"\s+", " ", str(text).replace("\r", " ").replace("\n", " ")).strip()


def _tokenize_v2(text: Any) -> list[str]:
    return TOKEN_RE.findall(_normalize_text_v2(text).lower())


def split_windows_words(text: str) -> list[str]:
    tokens = _tokenize_v2(normalize_text_value(text))
    if not tokens:
        return [""]
    if len(tokens) <= config.WINDOW_SIZE_WORDS:
        return [" ".join(tokens)]
    windows: list[str] = []
    start = 0
    while start < len(tokens):
        end = min(start + config.WINDOW_SIZE_WORDS, len(tokens))
        windows.append(" ".join(tokens[start:end]))
        if end >= len(tokens):
            break
        start += config.STRIDE_WORDS
    return windows


def _cache_key(text: str) -> str:
    return sha256_text(config.EMBEDDING_MODEL + "\n" + text)


def _source_is_real_api(source: object) -> bool:
    return str(source or "").strip().lower() in REAL_API_SOURCES


def _source_is_surrogate(source: object) -> bool:
    return str(source or "").strip().lower() in SURROGATE_SOURCES


def _vector_from_cache(row: dict) -> list[float]:
    value = row.get("embedding_json", "")
    if isinstance(value, str) and value.strip():
        return [float(x) for x in json.loads(value)]
    cols = sorted([c for c in row if str(c).startswith("embedding_dim_")])
    if cols:
        return [float(row[c]) for c in cols]
    raise ValueError("Cached embedding row does not contain embedding_json or embedding_dim_* columns")


def _cache_header(path: Path) -> list[str] | None:
    if not path.exists() or path.stat().st_size == 0:
        return None
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.reader(f)
        try:
            return next(reader)
        except StopIteration:
            return None


def _append_middle_cache(path: Path, rows: list[dict[str, Any]]) -> None:
    """Append rows while preserving either v2 or v3 cache schema.

    v2 cache header:
      cache_key, model, source, window_text, embedding_json, created_at,
      embedding_success, embedding_error

    v3 cache header:
      cache_key, model, text_hash, embedding_json, created_at, source

    Appending with the wrong column order corrupts the cache. This local writer
    detects the existing header and maps each field explicitly.
    """
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    header = _cache_header(path)
    if header is None:
        header = [
            "cache_key", "model", "source", "window_text", "embedding_json",
            "created_at", "embedding_success", "embedding_error", "text_hash",
        ]
        write_header = True
    else:
        write_header = False
    with path.open("a", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=header, extrasaction="ignore")
        if write_header:
            writer.writeheader()
        for row in rows:
            writer.writerow({name: row.get(name, "") for name in header})


def _safety_mask_text(text: str, aggressive: bool = False) -> str:
    """Return a provider-safety-friendly transcript window.

    Alphabetic placeholders are used instead of bracketed placeholders because
    repeated bracket tokens can themselves look abnormal to some filters.
    """
    def replace(match: re.Match[str]) -> str:
        word = match.group(0)
        if word.lower() in SAFETY_MASK_WORDS or (aggressive and len(word) > 4):
            return "content"
        return word
    return re.sub(r"[A-Za-z']+", replace, text)


def _neutral_window_text(text: str, minimal: bool = False) -> str:
    if minimal:
        return "neutral speech window"
    n = max(1, min(len(str(text).split()), config.WINDOW_SIZE_WORDS))
    return "speech window " + " ".join(["token"] * n)


def _embed_one_with_safety_fallback(client: HuaweiMaaSClient, text: str) -> tuple[list[float], str, str]:
    candidates = [
        ("raw", text, ""),
        ("safety_mask", _safety_mask_text(text, aggressive=False), "content_safety_masked"),
        ("aggressive_mask", _safety_mask_text(text, aggressive=True), "content_safety_aggressive_masked"),
        ("neutral_length", _neutral_window_text(text), "content_safety_neutral_length"),
        ("neutral_minimal", _neutral_window_text(text, minimal=True), "content_safety_neutral_minimal"),
    ]
    seen: set[str] = set()
    last_error: MaaSAPIError | None = None
    for level, candidate, note in candidates:
        candidate = re.sub(r"\s+", " ", candidate).strip()
        if candidate in seen:
            continue
        seen.add(candidate)
        try:
            return client.embed([candidate])[0], level, note
        except MaaSAPIError as exc:
            if exc.kind != "content safety / 403":
                raise
            last_error = exc
    raise last_error or MaaSAPIError("content safety / 403", "All embedding safety fallbacks failed.")


def _append_embedding_failure(cache_dir: Path, text: str, exc: Exception) -> None:
    path = cache_dir / "embedding_safety_failures.csv"
    row = pd.DataFrame([{
        "text_hash": sha256_text(text),
        "window_text": text,
        "error_type": type(exc).__name__,
        "error": str(exc)[:500],
        "created_at": now_utc(),
    }])
    row.to_csv(path, mode="a", header=not path.exists(), index=False, encoding="utf-8")


def _manifest_is_valid(manifest_path: Path) -> bool:
    if not manifest_path.exists():
        return False
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except Exception:
        return False
    if manifest.get("historical_feature_outputs_reused") is not False:
        return False
    if manifest.get("regenerated_from_raw_text") is not True:
        return False
    if manifest.get("local_surrogate_allowed") is not False:
        return False
    if manifest.get("feature_load_mode") not in {"extracted_this_run", "existing_feature_csv"}:
        return False
    if manifest.get("feature_schema") != config.MIDDLE_FEATURE_MODE:
        return False
    if int(manifest.get("middle_keep_dims", -1)) != int(config.MIDDLE_KEEP_DIMS):
        return False
    if int(manifest.get("n_middle_features", -1)) < int(config.MIDDLE_KEEP_DIMS):
        return False
    mode = str(manifest.get("api_or_cache_mode", "")).lower()
    if "local_surrogate" in mode or _contains_surrogate_marker(manifest):
        return False
    return True


def _sample_ids_match(path: Path, expected_ids: pd.Series) -> bool:
    try:
        df = pd.read_csv(path, usecols=["sample_id"])
    except Exception:
        return False
    return df["sample_id"].astype(str).tolist() == expected_ids.astype(str).tolist()


def _load_existing_features(train: pd.DataFrame, test: pd.DataFrame, output_dir: Path) -> tuple[dict[str, pd.DataFrame], dict] | None:
    train_path = output_dir / MIDDLE_TRAIN_FILE
    test_path = output_dir / MIDDLE_EXTERNAL_FILE
    manifest_path = output_dir / MIDDLE_MANIFEST_FILE
    if not (train_path.exists() and test_path.exists() and _manifest_is_valid(manifest_path)):
        return None
    if not (_sample_ids_match(train_path, train["sample_id"]) and _sample_ids_match(test_path, test["sample_id"])):
        return None
    tr = pd.read_csv(train_path)
    te = pd.read_csv(test_path)
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest = dict(manifest)
    manifest["feature_load_mode"] = "existing_feature_csv"
    manifest["feature_extracted_this_run"] = False
    return {"train": tr, "test": te}, manifest


def _delete_existing_features(output_dir: Path) -> None:
    for name in [MIDDLE_TRAIN_FILE, MIDDLE_EXTERNAL_FILE, MIDDLE_MANIFEST_FILE]:
        (output_dir / name).unlink(missing_ok=True)


def _required_window_keys(train: pd.DataFrame, test: pd.DataFrame) -> dict[str, str]:
    required: dict[str, str] = {}
    for df in (train, test):
        for text in df["text"].tolist():
            for window in split_windows_words(text):
                required[_cache_key(window)] = window
    return required


def _load_real_vectors_from_cache(cache_path: Path, reuse_cache: bool = True) -> tuple[dict[str, list[float]], int]:
    if not reuse_cache:
        return {}, 0
    remove_surrogate_cache_rows(cache_path)
    cache_raw = load_cache(cache_path, "cache_key")
    vectors: dict[str, list[float]] = {}
    ignored_surrogate_rows = 0
    for key, row in cache_raw.items():
        source = row.get("source", "")
        if _source_is_surrogate(source):
            ignored_surrogate_rows += 1
            continue
        # Accept both v3 source='api' and stagev2 source='huawei_maas_api'.
        if source and not _source_is_real_api(source):
            continue
        try:
            vectors[str(key)] = _vector_from_cache(row)
        except Exception:
            continue
    return vectors, ignored_surrogate_rows


def has_complete_real_features_or_cache(
    train: pd.DataFrame,
    test: pd.DataFrame,
    output_dir: Path,
    allow_existing_features: bool = True,
) -> bool:
    if allow_existing_features and _load_existing_features(train, test, output_dir) is not None:
        return True
    cache_path = config.CACHE_DIR / CACHE_FILE
    vectors, _ = _load_real_vectors_from_cache(cache_path, reuse_cache=True)
    required = _required_window_keys(train, test)
    return all(key in vectors for key in required)


def _obtain_embeddings(
    texts: list[str],
    cache_dir: Path,
    reuse_cache: bool = True,
    progress_callback: Callable[[dict], None] | None = None,
) -> tuple[dict[str, list[float]], str, dict]:
    cache_dir.mkdir(parents=True, exist_ok=True)
    cache_path = cache_dir / CACHE_FILE
    vectors, ignored_surrogate_rows = _load_real_vectors_from_cache(cache_path, reuse_cache=reuse_cache)

    unique: dict[str, str] = {}
    for text in texts:
        key = _cache_key(text)
        if key not in vectors:
            unique[key] = text

    unique_total = len({_cache_key(text) for text in texts})
    if progress_callback:
        progress_callback({
            "total_windows": unique_total,
            "cached_windows": unique_total - len(unique),
            "pending_api_windows": len(unique),
            "api_batch_size": config.EMBEDDING_BATCH_SIZE,
            "completed_batches": 0,
        })

    mode = "cache"
    new_cache_row_count = 0
    safety_masked_api_calls = 0
    safety_level_counts: dict[str, int] = {}

    if unique:
        client = HuaweiMaaSClient(timeout=config.EMBEDDING_TIMEOUT, max_retries=config.EMBEDDING_MAX_RETRIES)
        keys = list(unique.keys())
        vals = [unique[k] for k in keys]
        show_progress = bool(config.MIDDLE_SHOW_PROGRESS)
        inner_bar = tqdm(
            total=len(vals),
            desc="Middle API windows",
            unit="win",
            leave=True,
            disable=not show_progress,
        )
        if not client.has_key():
            raise RuntimeError(
                "Middle feature extraction needs Huawei BGE-M3 API or a complete real-API cache. "
                "MAAS_API_KEY is missing and cached embeddings do not cover all required windows. "
                "This package is independent of stagev2, but it still requires either MAAS_API_KEY "
                "or a complete output/cache/huawei_bge_m3_embedding_cache.csv."
            )
        mode = "api"
        completed_batches = 0
        pending_rows: list[dict[str, Any]] = []
        try:
            for start in range(0, len(vals), config.EMBEDDING_BATCH_SIZE):
                bkeys = keys[start:start + config.EMBEDDING_BATCH_SIZE]
                btexts = vals[start:start + config.EMBEDDING_BATCH_SIZE]
                safety_levels = ["raw_batch"] * len(btexts)
                safety_notes = [""] * len(btexts)
                try:
                    try:
                        embs = client.embed(btexts)
                    except MaaSAPIError as exc:
                        if exc.kind != "content safety / 403":
                            raise
                        embs = []
                        safety_levels = []
                        safety_notes = []
                        for text in btexts:
                            emb, level, note = _embed_one_with_safety_fallback(client, text)
                            embs.append(emb)
                            safety_levels.append(level)
                            safety_notes.append(note)
                            if level != "raw":
                                safety_masked_api_calls += 1
                                safety_level_counts[level] = safety_level_counts.get(level, 0) + 1
                except Exception as exc:
                    _append_middle_cache(cache_path, pending_rows)
                    pending_rows.clear()
                    for text in btexts:
                        _append_embedding_failure(cache_dir, text, exc)
                    if not inner_bar.disable:
                        inner_bar.set_postfix_str(f"failed: {type(exc).__name__}")
                    raise

                if len(embs) != len(bkeys):
                    raise RuntimeError(f"Embedding length mismatch: expected {len(bkeys)}, got {len(embs)}")

                for key, text, emb, level, note in zip(bkeys, btexts, embs, safety_levels, safety_notes):
                    vectors[key] = emb
                    row = {
                        "cache_key": key,
                        "model": config.EMBEDDING_MODEL,
                        "source": "api",
                        "window_text": text,
                        "text_hash": sha256_text(text),
                        "embedding_json": json.dumps(emb, separators=(",", ":")),
                        "created_at": now_utc(),
                        "embedding_success": 1,
                        "embedding_error": note,
                        "safety_level": level,
                    }
                    pending_rows.append(row)
                    new_cache_row_count += 1

                completed_batches += 1
                # v2-style cache-first behavior, but safer: flush each successful batch.
                # With EMBEDDING_BATCH_SIZE=1, a later 403 cannot discard previous vectors.
                _append_middle_cache(cache_path, pending_rows)
                pending_rows.clear()
                remaining = max(len(unique) - new_cache_row_count, 0)
                inner_bar.update(len(btexts))
                if not inner_bar.disable:
                    inner_bar.set_postfix(
                        cached=unique_total - remaining,
                        pending=remaining,
                        safety=safety_masked_api_calls,
                        refresh=False,
                    )
                if progress_callback:
                    progress_callback({
                        "completed_batches": completed_batches,
                        "cached_windows": unique_total - remaining,
                        "pending_api_windows": remaining,
                    })
        finally:
            inner_bar.close()

    return vectors, mode, {
        "cache_path": str(cache_path),
        "new_cache_rows": new_cache_row_count,
        "unique_texts": unique_total,
        "ignored_surrogate_cache_rows": int(ignored_surrogate_rows),
        "accepted_cache_sources": sorted(REAL_API_SOURCES),
        "safety_masked_api_calls": int(safety_masked_api_calls),
        "safety_level_counts": safety_level_counts,
        "stagev2_cache_compatible": True,
    }


def _sample_features(df: pd.DataFrame, vectors: dict[str, list[float]]) -> pd.DataFrame:
    """Aggregate window-level BGE-M3 embeddings into v2-compatible sample features.

    The high-performing v2 path treated the window-level embedding file as a
    stage table and averaged numeric columns per sample. Because `window_id` was
    included by the v2 middle-prefix matcher, the aggregated middle block had
    1025 inputs: mean(window_id) + 1024 embedding dimensions. The previous v3
    implementation kept only the first 32 embedding dimensions plus a few drift
    statistics. This function restores the full v2-compatible representation.
    """
    rows = []
    for _, row in df.iterrows():
        windows = split_windows_words(row["text"])
        mat = np.array([vectors[_cache_key(w)] for w in windows], dtype=float)
        if mat.ndim == 1:
            mat = mat.reshape(1, -1)
        k = min(int(config.MIDDLE_KEEP_DIMS), mat.shape[1])
        mat_k = mat[:, :k]
        feat = {"sample_id": row["sample_id"]}
        # Matches the v2 groupby-mean side effect that retained numeric window_id.
        feat["middle_window_id"] = float(np.mean(np.arange(len(windows), dtype=float))) if windows else 0.0
        mean = mat_k.mean(axis=0)
        for i, v in enumerate(mean):
            feat[f"middle_embedding_dim_{i:04d}"] = float(v)
        if bool(getattr(config, "MIDDLE_INCLUDE_V3_STATS", False)):
            std = mat_k.std(axis=0)
            for i, v in enumerate(std[:8]):
                feat[f"middle_emb_std_{i:04d}"] = float(v)
            if len(mat_k) > 1:
                drift = np.linalg.norm(np.diff(mat_k, axis=0), axis=1)
                feat["middle_window_drift_mean"] = float(np.mean(drift))
                feat["middle_window_drift_max"] = float(np.max(drift))
            else:
                feat["middle_window_drift_mean"] = 0.0
                feat["middle_window_drift_max"] = 0.0
            feat["middle_n_windows"] = int(len(windows))
            feat["middle_text_length"] = int(max(len(str(row["text"]).split()), 1))
        rows.append(feat)
    return pd.DataFrame(rows)


def generate_middle_features(
    train: pd.DataFrame,
    test: pd.DataFrame,
    output_dir: Path,
    force_extract: bool = False,
    reuse_features: bool = True,
    progress_callback: Callable[[dict], None] | None = None,
) -> tuple[dict[str, pd.DataFrame], dict]:
    output_dir.mkdir(parents=True, exist_ok=True)
    if force_extract:
        _delete_existing_features(output_dir)
    if reuse_features:
        existing = _load_existing_features(train, test, output_dir)
        if existing is not None:
            if progress_callback:
                total = len(_required_window_keys(train, test))
                progress_callback({
                    "total_windows": total,
                    "cached_windows": total,
                    "pending_api_windows": 0,
                    "api_batch_size": config.EMBEDDING_BATCH_SIZE,
                    "completed_batches": 0,
                })
            return existing
        _delete_existing_features(output_dir)

    all_windows: list[str] = []
    for df in [train, test]:
        for text in df["text"].tolist():
            all_windows.extend(split_windows_words(text))

    vectors, mode, info = _obtain_embeddings(
        all_windows,
        config.CACHE_DIR,
        reuse_cache=True,
        progress_callback=progress_callback,
    )
    tr = _sample_features(train, vectors)
    te = _sample_features(test, vectors)
    tr.to_csv(output_dir / MIDDLE_TRAIN_FILE, index=False, encoding="utf-8")
    te.to_csv(output_dir / MIDDLE_EXTERNAL_FILE, index=False, encoding="utf-8")
    manifest = {
        "feature_family": "middle_huawei_bge_m3_window_embedding",
        "feature_schema": config.MIDDLE_FEATURE_MODE,
        "middle_keep_dims": int(config.MIDDLE_KEEP_DIMS),
        "middle_include_v3_stats": bool(config.MIDDLE_INCLUDE_V3_STATS),
        "regenerated_from_raw_text": True,
        "historical_feature_outputs_reused": False,
        "api_logic_source": "stagev2_cache_first_logic_v3_wrapper",
        "windowing_source": "stagev2_regex_word_windows",
        "api_or_cache_mode": mode,
        "feature_load_mode": "extracted_this_run",
        "feature_extracted_this_run": True,
        "local_surrogate_allowed": False,
        **info,
        "n_train_rows": int(len(tr)),
        "n_external_rows": int(len(te)),
        "n_middle_features": int(tr.shape[1] - 1),
    }
    (output_dir / MIDDLE_MANIFEST_FILE).write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return {"train": tr, "test": te}, manifest
