"""Stagev5 feature orchestration.

This module never redefines E, M, or L. It calls the copied source implementations:
- E and M: exact stagev2 files under ``src/reference_stagev2``;
- L: exact stagev4_unmasked P4/F8 files under ``src/reference_stagev4``.

Only output paths, sample-ID checks, and stagev2 classifier file layout are handled here.
"""
from __future__ import annotations

import hashlib
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd

from . import stagev5_config as cfg
from .reference_stagev2.stagev1_features import FEATURE_VERSION, generate_all_early_features
from .reference_stagev2.api_feature_extraction import run_middle_embeddings
from .reference_stagev4 import config as v4_config
from .reference_stagev4.late_extract import extract_late_scores
from .reference_stagev4.late_prompt import RAW8_COLUMNS

LATE_RAW_F8_BASE_NAMES = [
    "sentence_structural_integrity",
    "phrase_continuity",
    "repetition_control",
    "repair_efficiency",
    "filler_control",
    "referential_clarity",
    "grammatical_stability",
    "local_coherence",
]

LATE_RAW_F8_COLUMNS = [f"late_{name}" for name in LATE_RAW_F8_BASE_NAMES]
LATE_AUXILIARY_ACTIVATION_POLICY = "raw_F8_mean"


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _utc() -> str:
    return datetime.now(timezone.utc).isoformat()


def resolve_late_raw_f8_columns(df: pd.DataFrame) -> list[str]:
    """Resolve the strict stagev4_unmasked raw F8 columns in canonical order."""
    resolved: list[str] = []
    for base_name in LATE_RAW_F8_BASE_NAMES:
        prefixed = f"late_{base_name}"
        candidates = [c for c in (prefixed, base_name) if c in df.columns]
        if len(candidates) != 1:
            raise ValueError(
                {
                    "error": "late_raw_F8_column_resolution_failed",
                    "base_name": base_name,
                    "expected_one_of": [prefixed, base_name],
                    "matches": candidates,
                    "available_late_related_columns": [c for c in df.columns if c.startswith("late_") or c == base_name],
                }
            )
        resolved.append(candidates[0])
    if len(set(resolved)) != len(resolved):
        raise ValueError({"error": "late_raw_F8_duplicate_columns", "late_raw_F8_columns": resolved})
    return resolved


def resolve_late_auxiliary_columns(df: pd.DataFrame, late_raw_f8_cols: list[str] | None = None) -> list[str]:
    """Return late diagnostic columns that are retained but never used as model input."""
    raw = set(late_raw_f8_cols or resolve_late_raw_f8_columns(df))
    auxiliary: list[str] = []
    for c in df.columns:
        if c in raw or not c.startswith("late_") or c.startswith("late_llm_"):
            continue
        if pd.api.types.is_numeric_dtype(df[c]):
            auxiliary.append(c)
    return auxiliary


def _late_validation_summary(df: pd.DataFrame, name: str) -> dict[str, Any]:
    raw_f8 = resolve_late_raw_f8_columns(df)
    auxiliary = resolve_late_auxiliary_columns(df, raw_f8)
    all_related = raw_f8 + auxiliary
    return {
        "name": name,
        "late_all_related_cols": all_related,
        "late_raw_f8_cols": raw_f8,
        "late_auxiliary_cols": auxiliary,
        "late_model_feature_count": len(raw_f8),
        "late_diagnostic_column_count": len(auxiliary),
        "late_auxiliary_used_in_model": False,
        "late_activation_policy": LATE_AUXILIARY_ACTIVATION_POLICY,
    }


def _ensure_dirs() -> None:
    for p in [cfg.EARLY_DIR, cfg.MIDDLE_DIR, cfg.LATE_DIR, cfg.STAGEV2_EXTRACT_ROOT, cfg.STAGEV4_EXTRACT_ROOT, cfg.FINAL]:
        p.mkdir(parents=True, exist_ok=True)


def _copy_reference_middle_cache(force: bool = False) -> Path | None:
    """Copy the stagev2 embedding cache to stagev5's local runtime cache once.

    This is a cache-only acceleration artifact. The actual M feature matrix is still
    regenerated by stagev2's original ``run_middle_embeddings`` function.
    """
    if not cfg.ASSET_CACHE.exists():
        return None
    target = cfg.STAGEV2_EXTRACT_ROOT / "cache" / "huawei_bge_m3_embedding_cache.csv"
    target.parent.mkdir(parents=True, exist_ok=True)
    if force or not target.exists():
        shutil.copy2(cfg.ASSET_CACHE, target)
    return target


def _clean_feature_dir(path: Path, force: bool) -> None:
    if force and path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def extract_E_M(force: bool = False, reuse_reference_cache: bool = True) -> dict[str, Any]:
    """Run stagev2 E/M extraction without altering source definitions."""
    _ensure_dirs()
    if force and cfg.STAGEV2_EXTRACT_ROOT.exists():
        shutil.rmtree(cfg.STAGEV2_EXTRACT_ROOT)
    cfg.STAGEV2_EXTRACT_ROOT.mkdir(parents=True, exist_ok=True)
    cache = _copy_reference_middle_cache(force=False) if reuse_reference_cache else None

    # Exact stagev2 early function: preprocess, train-only BM25 fit, and E CSV generation.
    preprocessed, early_dir, early_manifest = generate_all_early_features(
        cfg.INPUT_RAW,
        cfg.STAGEV2_EXTRACT_ROOT,
        FEATURE_VERSION,
    )

    # Exact stagev2 middle function: original 15-word/stride-5 BGE-M3 windows and cache semantics.
    middle_dir = cfg.STAGEV2_EXTRACT_ROOT / "features" / "embedding"
    cache_dir = cfg.STAGEV2_EXTRACT_ROOT / "cache"
    middle_manifest = run_middle_embeddings(preprocessed, middle_dir, cache_dir, reuse_cache=True)

    mapping_e = {"ad_BM25.csv": "ad_BM25.csv", "control_BM25.csv": "control_BM25.csv", "test_BM25.csv": "test_BM25.csv"}
    for src_name, dst_name in mapping_e.items():
        src = early_dir / src_name
        if not src.exists():
            raise FileNotFoundError(f"Stagev2 early output is missing: {src}")
        shutil.copy2(src, cfg.EARLY_DIR / dst_name)
    mapping_m = {"ad_embedding.csv": "ad_embedding.csv", "control_embedding.csv": "control_embedding.csv", "test_embedding.csv": "test_embedding.csv"}
    for src_name, dst_name in mapping_m.items():
        src = middle_dir / src_name
        if not src.exists():
            raise FileNotFoundError(f"Stagev2 middle output is missing: {src}")
        shutil.copy2(src, cfg.MIDDLE_DIR / dst_name)

    info = {
        "source_project": "stagev2.zip",
        "early_source_function": "src.stagev1_features.generate_all_early_features",
        "middle_source_function": "src.api_feature_extraction.run_middle_embeddings",
        "early_feature_version": FEATURE_VERSION,
        "middle_window_policy": "stagev2 exact: 15 words, stride 5, bge-m3",
        "reference_middle_cache_used": bool(cache and cache.exists()),
        "early_manifest": early_manifest,
        "middle_manifest": middle_manifest,
        "created_at": _utc(),
    }
    (cfg.FEATURE_ROOT / "E_M_extraction_manifest.json").write_text(json.dumps(info, ensure_ascii=False, indent=2, default=str), encoding="utf-8")
    return {"preprocessed": preprocessed, "manifest": info}


def _configure_stagev4_runtime() -> None:
    """Redirect only stagev4 runtime paths; P4 prompt/scoring code is unmodified."""
    runtime = cfg.STAGEV4_EXTRACT_ROOT
    v4_config.ROOT = cfg.ROOT
    v4_config.INPUT_DIR = cfg.ROOT / "input"
    v4_config.RAW_DIR = cfg.INPUT_RAW
    v4_config.FROZEN_DIR = cfg.V4_META_DIR
    v4_config.CONFIG_DIR = cfg.ROOT / "configs" / "reference_stagev4"
    v4_config.OUTPUT_DIR = runtime
    v4_config.CACHE_DIR = runtime / "cache"
    v4_config.FEATURE_DIR = runtime / "features"
    v4_config.DIAGNOSTICS_DIR = runtime / "diagnostics"
    v4_config.METRICS_DIR = runtime / "metrics"
    v4_config.FIGURES_DIR = runtime / "figures"
    v4_config.FINAL_DIR = runtime / "final_report"
    v4_config.LOG_DIR = runtime / "logs"
    v4_config.SUMMARY_DIR = runtime / "summary"


def _load_v4_metadata() -> tuple[pd.DataFrame, pd.DataFrame]:
    train = pd.read_csv(cfg.V4_META_DIR / "train_metadata.csv")
    external = pd.read_csv(cfg.V4_META_DIR / "external_metadata.csv")
    for name, df in [("train", train), ("external", external)]:
        required = {"sample_id", "text", "label", "mmse"}
        missing = required.difference(df.columns)
        if missing:
            raise ValueError(f"Stagev4 {name} metadata is missing columns: {sorted(missing)}")
        if df["sample_id"].astype(str).duplicated().any():
            raise ValueError(f"Stagev4 {name} metadata has duplicate sample IDs.")
    return train, external


def _write_stagev2_compatible_late(late_train: pd.DataFrame, late_external: pd.DataFrame) -> None:
    # Stagev2 classifier core expects ad/control/test split files.  The F8 values are copied unchanged.
    raw_f8_cols_train = resolve_late_raw_f8_columns(late_train)
    raw_f8_cols_external = resolve_late_raw_f8_columns(late_external)
    if raw_f8_cols_train != raw_f8_cols_external:
        raise ValueError(
            {
                "error": "late_raw_F8_train_external_mismatch",
                "train_late_raw_F8_columns": raw_f8_cols_train,
                "external_late_raw_F8_columns": raw_f8_cols_external,
            }
        )
    for col in raw_f8_cols_train:
        if col not in late_train or col not in late_external:
            raise ValueError(f"Missing required P4/F8 late feature: {col}")
    tr = late_train.copy()
    ex = late_external.copy()
    if "label" not in tr:
        raise ValueError("Stagev4 train late scores cannot be split into AD/control without label.")
    for split_name, sub in [("ad_LLM.csv", tr.loc[tr["label"].astype(int).eq(1)]), ("control_LLM.csv", tr.loc[tr["label"].astype(int).eq(0)]), ("test_LLM.csv", ex)]:
        auxiliary_cols = resolve_late_auxiliary_columns(sub, raw_f8_cols_train)
        keep = [c for c in ["sample_id", "label", "mmse", "split", "mask_version", "prompt_version", "prompt_hash", "text_hash", "scored_text_hash", "scored_text", "late_llm_source", "late_llm_attempts", *raw_f8_cols_train, *auxiliary_cols] if c in sub.columns]
        out = sub.loc[:, keep].copy()
        out.to_csv(cfg.LATE_DIR / split_name, index=False, encoding="utf-8")


def extract_L(force: bool = False) -> dict[str, Any]:
    """Run P4 unmasked F8 L extraction using the copied stagev4 source module."""
    _ensure_dirs()
    _configure_stagev4_runtime()
    train_meta, external_meta = _load_v4_metadata()
    late_train = extract_late_scores(train_meta, "train", force=force)
    late_external = extract_late_scores(external_meta, "external", force=force)
    # Attach labels only after source scoring; they are never part of the LLM prompt.
    late_train = train_meta[["sample_id", "label", "mmse"]].merge(late_train, on="sample_id", how="inner", validate="one_to_one")
    late_external = external_meta[["sample_id", "label", "mmse"]].merge(late_external, on="sample_id", how="inner", validate="one_to_one")
    _write_stagev2_compatible_late(late_train, late_external)
    info = {
        "source_project": "stagev4_unmasked_form_comparator.zip",
        "late_source_function": "src.late_extract.extract_late_scores",
        "prompt_version": v4_config.LATE_PROMPT_VERSION,
        "mask_version": v4_config.LATE_MASK_VERSION,
        "dimension_version": v4_config.LATE_DIMENSION_VERSION,
        "raw8_columns": resolve_late_raw_f8_columns(late_train),
        "raw8_base_names": LATE_RAW_F8_BASE_NAMES,
        "late_auxiliary_columns_train": resolve_late_auxiliary_columns(late_train),
        "late_auxiliary_columns_external": resolve_late_auxiliary_columns(late_external),
        "late_auxiliary_used_in_model": False,
        "late_activation_policy": LATE_AUXILIARY_ACTIVATION_POLICY,
        "score_levels": sorted(v4_config.LATE_ALLOWED_VALUES),
        "created_at": _utc(),
    }
    (cfg.FEATURE_ROOT / "L_extraction_manifest.json").write_text(json.dumps(info, ensure_ascii=False, indent=2), encoding="utf-8")
    return info


def expected_feature_paths() -> dict[str, list[Path]]:
    return {
        "E": [cfg.EARLY_DIR / x for x in ("ad_BM25.csv", "control_BM25.csv", "test_BM25.csv")],
        "M": [cfg.MIDDLE_DIR / x for x in ("ad_embedding.csv", "control_embedding.csv", "test_embedding.csv")],
        "L": [cfg.LATE_DIR / x for x in ("ad_LLM.csv", "control_LLM.csv", "test_LLM.csv")],
    }


def validate_feature_outputs() -> dict[str, Any]:
    paths = expected_feature_paths()
    missing = [str(p) for family in paths.values() for p in family if not p.exists()]
    if missing:
        raise FileNotFoundError("Missing extracted feature outputs:\n" + "\n".join(missing))
    e = pd.read_csv(paths["E"][0])
    m = pd.read_csv(paths["M"][0])
    early_cols = [c for c in e.columns if c.startswith("early_")]
    middle_cols = [c for c in m.columns if c.startswith("embedding_dim_")]
    late_summaries = [_late_validation_summary(pd.read_csv(path), path.name) for path in paths["L"]]
    late_raw_f8_cols = late_summaries[0]["late_raw_f8_cols"]
    late_auxiliary_cols = late_summaries[0]["late_auxiliary_cols"]
    raw_mismatches = [s for s in late_summaries if s["late_raw_f8_cols"] != late_raw_f8_cols]
    auxiliary_consistent = all(s["late_auxiliary_cols"] == late_auxiliary_cols for s in late_summaries)
    if len(early_cols) != 61 or len(middle_cols) != 1024 or len(late_raw_f8_cols) != 8 or raw_mismatches:
        raise ValueError(
            {
                "expected_E": 61,
                "actual_E": len(early_cols),
                "expected_M": 1024,
                "actual_M": len(middle_cols),
                "expected_L_raw_F8": 8,
                "actual_L_raw_F8": len(late_raw_f8_cols),
                "late_raw_F8_columns": late_raw_f8_cols,
                "late_auxiliary_columns": late_auxiliary_cols,
                "late_raw_F8_mismatches": raw_mismatches,
            }
        )
    return {
        "n_E": len(early_cols),
        "n_M": len(middle_cols),
        "n_L": len(late_raw_f8_cols),
        "expected_E": 61,
        "actual_E": len(early_cols),
        "expected_M": 1024,
        "actual_M": len(middle_cols),
        "expected_L_raw_F8": 8,
        "actual_L_raw_F8": len(late_raw_f8_cols),
        "late_raw_F8_columns": late_raw_f8_cols,
        "late_auxiliary_columns": late_auxiliary_cols,
        "late_all_related_cols": late_summaries[0]["late_all_related_cols"],
        "late_model_feature_count": len(late_raw_f8_cols),
        "late_diagnostic_column_count": len(late_auxiliary_cols),
        "late_auxiliary_used_in_model": False,
        "late_auxiliary_columns_consistent": auxiliary_consistent,
        "late_split_summaries": late_summaries,
        "late_activation_policy": LATE_AUXILIARY_ACTIVATION_POLICY,
        "paths": {k: [str(p) for p in v] for k, v in paths.items()},
    }
