"""Markdown report generation."""
from __future__ import annotations

import json
import pandas as pd


def _fmt(x):
    try:
        if pd.isna(x):
            return "NA"
        return f"{float(x):.6f}"
    except Exception:
        return str(x)


def choose_recommendations(external: pd.DataFrame) -> dict:
    ranking = external.sort_values(
        ["accuracy", "balanced_accuracy", "sensitivity", "specificity", "f1", "roc_auc", "pr_auc"],
        ascending=False,
    )
    best = ranking.iloc[0]
    mech_df = ranking[ranking["mechanism_consistent"] == True].copy()
    mech = mech_df.iloc[0] if len(mech_df) else best
    return {
        "best_external_accuracy_model": best["model_name"],
        "best_mechanism_consistent_model": mech["model_name"],
        "final_recommended_model": best["model_name"],
        "selection_metric": "external_accuracy",
        "recommendation_rule": "Selected the model with highest held-out external accuracy; ties are resolved by balanced accuracy, sensitivity, specificity, F1, ROC-AUC, and PR-AUC.",
    }


def _top_table(df: pd.DataFrame, cols: list[str], n: int = 30) -> str:
    use_cols = [c for c in cols if c in df.columns]
    if not use_cols:
        return "No table available."
    return df[use_cols].head(n).to_markdown(index=False)


def write_report(dirs: dict, external: pd.DataFrame, cv_results: pd.DataFrame, gap: pd.DataFrame, errors: dict, recommendations: dict, schema: dict, source_info: dict) -> None:
    path = dirs["reports"] / "stagev2_experiment_report.md"
    with path.open("w", encoding="utf-8") as f:
        f.write("# stagev2 AD classifier experiment report\n\n")
        f.write("## Purpose\n")
        f.write(
            "This run evaluates early, middle, late, fused, and sequential-interaction classifiers. "
            "Early BM25 features represent Cookie Theft information-unit capture; middle BGE-M3 features represent semantic integration; "
            "late qwen3-235b-a22b expressive-form scores represent connected-speech production quality after content masking.\n\n"
        )
        f.write("## Confirmed experimental policy\n")
        f.write("- Main label order: `[disease, early, middle, late]`.\n")
        f.write("- MMSE thresholds: early/mild = 21-24, middle/moderate = 13-20, late/severe = <=12.\n")
        f.write("- Raw data are the only input. Early, middle, and late features are regenerated by this project.\n")
        f.write("- Historical outputs, historical features, old cache files, and old model files are not reused.\n")
        f.write("- Models are ranked and selected by held-out external accuracy.\n")
        f.write("- CV and OOF predictions are internal diagnostics, not the final selection rule.\n")
        f.write("- The external set is treated as held-out external validation, not as an unbiased final test after model selection.\n")
        f.write("- RBF SVM is included as a nonlinear baseline.\n")
        f.write("- MMSE is used only for severity grouping, not as an input feature.\n\n")

        f.write("## Data and feature counts\n")
        f.write(f"- Early features used: {schema['n_early']}\n")
        f.write(f"- Middle features used: {schema['n_middle']}\n")
        f.write(f"- Late features used: {schema['n_late']}\n")
        f.write(f"- Train samples: {source_info.get('n_train', 'NA')}\n")
        f.write(f"- External validation samples: {source_info.get('n_test', 'NA')}\n\n")

        f.write("## Selected model\n")
        for k, v in recommendations.items():
            f.write(f"- **{k}**: {v}\n")
        sel = external[external["model_name"] == recommendations["final_recommended_model"]]
        if not sel.empty:
            row = sel.iloc[0]
            f.write(f"- **external_accuracy**: {_fmt(row.get('accuracy'))}\n")
            f.write(f"- **external_balanced_accuracy**: {_fmt(row.get('balanced_accuracy'))}\n")
            f.write(f"- **sensitivity**: {_fmt(row.get('sensitivity'))}\n")
            f.write(f"- **specificity**: {_fmt(row.get('specificity'))}\n")
        f.write("\n")

        f.write("## Top models by external accuracy\n")
        ext_cols = ["model_name", "group", "feature_block", "accuracy", "balanced_accuracy", "sensitivity", "specificity", "f1", "roc_auc", "pr_auc", "mcc", "tn", "fp", "fn", "tp"]
        f.write(_top_table(external, ext_cols, 30))
        f.write("\n\n")

        f.write("## CV diagnostic summary\n")
        cv_cols = ["model_name", "group", "feature_block", "cv_accuracy", "cv_balanced_accuracy", "cv_sensitivity", "cv_specificity", "cv_f1", "cv_roc_auc", "cv_pr_auc", "cv_mcc", "best_cv_score_grid"]
        f.write(_top_table(cv_results, cv_cols, 30))
        f.write("\n\n")

        f.write("## Generalization diagnostic\n")
        gap_cols = ["model_name", "cv_accuracy", "external_accuracy", "accuracy_gap", "cv_balanced_accuracy", "external_balanced_accuracy", "balanced_accuracy_gap"]
        f.write(_top_table(gap, gap_cols, 30))
        f.write("\n\n")

        f.write("## Severity/subgroup accuracy summary\n")
        sev = errors.get("severity_accuracy", pd.DataFrame())
        f.write(sev.to_markdown(index=False) if not sev.empty else "No severity table generated.")
        f.write("\n\n")

        f.write("## Hard false positives\n")
        hfp = errors.get("hard_false_positive", pd.DataFrame())
        f.write(hfp.head(30).to_markdown(index=False) if not hfp.empty else "No hard false positives above the configured threshold.")
        f.write("\n\n")

        f.write("## Hard false negatives\n")
        hfn = errors.get("hard_false_negative", pd.DataFrame())
        f.write(hfn.head(30).to_markdown(index=False) if not hfn.empty else "No hard false negatives above the configured threshold.")
        f.write("\n\n")

        f.write("## Canonical outputs\n")
        f.write("- `tables/stagev2_model_ranking_by_external_accuracy.csv`\n")
        f.write("- `tables/stagev2_external_performance_report.csv`\n")
        f.write("- `tables/stagev2_cv_summary.csv`\n")
        f.write("- `predictions/stagev2_oof_predictions_top10.csv`\n")
        f.write("- `predictions/stagev2_test_predictions_all_models.csv`\n")
        f.write("- `reports/stagev2_selected_model_summary.md`\n")
        f.write("- `reports/stagev2_experiment_report.md`\n")
        f.write("- `reports/stagev2_leakage_check.json`\n")

    selected_summary_path = dirs["reports"] / "stagev2_selected_model_summary.md"
    with selected_summary_path.open("w", encoding="utf-8") as f:
        f.write("# stagev2 selected model summary\n\n")
        for k, v in recommendations.items():
            f.write(f"- **{k}**: {v}\n")
        sel = external[external["model_name"] == recommendations["final_recommended_model"]]
        if not sel.empty:
            f.write("\n## External validation metrics\n\n")
            cols = ["model_name", "accuracy", "balanced_accuracy", "sensitivity", "specificity", "f1", "roc_auc", "pr_auc", "mcc", "tn", "fp", "fn", "tp"]
            f.write(sel[[c for c in cols if c in sel.columns]].to_markdown(index=False))
            f.write("\n")

    with (dirs["reports"] / "stagev2_recommendations.json").open("w", encoding="utf-8") as fjson:
        json.dump(recommendations, fjson, ensure_ascii=False, indent=2)
