from __future__ import annotations

import shutil
import zipfile
from pathlib import Path

REQUIRED_RAW_FILES = [
    "ad_s2t_wav2vec.csv",
    "control_s2t_wav2vec.csv",
    "test_s2t_wav2vec.csv",
]


def _contains_required_files(path: Path) -> bool:
    return path.is_dir() and all((path / name).is_file() for name in REQUIRED_RAW_FILES)


def validate_raw_source(data_root: Path | None, data_zip: Path | None = None) -> None:
    """Validate raw input before any existing output is removed."""
    if data_zip is not None:
        if not data_zip.is_file():
            raise FileNotFoundError(f"--data-zip does not exist: {data_zip}")
        if not zipfile.is_zipfile(data_zip):
            raise ValueError(f"--data-zip is not a valid zip file: {data_zip}")
        with zipfile.ZipFile(data_zip, "r") as zf:
            names = {Path(name).name for name in zf.namelist()}
        missing = [name for name in REQUIRED_RAW_FILES if name not in names]
        if missing:
            raise FileNotFoundError(f"{data_zip} is missing required raw files: {missing}")
        return

    root = data_root or Path("input/raw")
    candidates = [root, root / "input", root / "raw"]
    if any(_contains_required_files(candidate) for candidate in candidates):
        return
    raise FileNotFoundError(
        "Cannot locate raw input CSV files. Expected all of "
        f"{REQUIRED_RAW_FILES} under one of: {[str(candidate) for candidate in candidates]}"
    )


def _safe_extract_raw_input(zip_path: Path, extract_root: Path) -> Path:
    """Extract only the raw input CSVs from a zip into extract_root/input.

    Historical outputs, caches, generated features, and model files inside the zip are
    intentionally ignored. This enforces the project rule: raw data in, all features
    regenerated by the current code.
    """
    extract_root.mkdir(parents=True, exist_ok=True)
    input_out = extract_root / "input"
    input_out.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(zip_path, "r") as zf:
        names = zf.namelist()
        for required in REQUIRED_RAW_FILES:
            matches = [n for n in names if Path(n).name == required]
            if not matches:
                raise FileNotFoundError(f"{zip_path} does not contain required raw file: {required}")
            # Prefer a member under an input/ folder if available.
            member = sorted(matches, key=lambda n: ("/input/" not in n.replace("\\", "/"), len(n)))[0]
            target = input_out / required
            with zf.open(member) as src, target.open("wb") as dst:
                shutil.copyfileobj(src, dst)
    return input_out


def prepare_raw_input(
    data_root: Path | None,
    output_root: Path,
    data_zip: Path | None = None,
    force_extract: bool = True,
) -> tuple[Path, dict]:
    """Return a directory containing the three raw CSV files.

    No generated features or historical outputs are accepted as input.
    """
    output_root = output_root.resolve()
    source_root = output_root / "source_raw"
    info: dict[str, str] = {}

    if data_zip is not None:
        zip_path = data_zip.resolve()
        validate_raw_source(None, zip_path)
        if force_extract and source_root.exists():
            shutil.rmtree(source_root)
        input_dir = _safe_extract_raw_input(zip_path, source_root)
        info.update({
            "data_source_mode": "zip_raw_extract",
            "data_zip": str(zip_path),
            "raw_input_dir": str(input_dir),
            "historical_outputs_reused": "False",
        })
        return input_dir, info

    if data_root is None:
        data_root = Path("input/raw")
    validate_raw_source(data_root)
    root = data_root.resolve()
    candidates = [root, root / "input", root / "raw"]
    for cand in candidates:
        if _contains_required_files(cand):
            info.update({
                "data_source_mode": "raw_directory",
                "raw_input_dir": str(cand),
                "historical_outputs_reused": "False",
            })
            return cand, info

    raise FileNotFoundError(
        "Cannot locate raw input CSV files. Provide either:\n"
        "  --data-root path/to/folder/with/ad_s2t_wav2vec.csv/control_s2t_wav2vec.csv/test_s2t_wav2vec.csv\n"
        "or:\n"
        "  --data-zip path/to/archive.zip containing those raw files."
    )
